# Name of Action
name: shutdown

# Controls when the action will run. 
on:
  
  # If you want to trigger this on push to a branch uncomment below
  # push:
  #  branches: [ main ]
  
  # This allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Below this are each of the steps that are run
    steps:
    
      # Name of step
      - name: Stop AWS EC2
        # Run AWS Command on the GitHub Hosted runner which stops the instance using AWS authentication stored in GitHub Secrets (see below how to add)
        run: |
          export AWS_REGION=ap-south-1
          export AWS_DEFAULT_REGION=ap-south-1
          export AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws ec2 start-instances --region ap-south-1 --instance-ids i-06b298be9ed00ddb8
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
