name: EC2 Control

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action (start or stop)'
        required: true
        default: 'start'

jobs:
  control-ec2:
    runs-on: ubuntu-latest
    steps:
      - name: Start or Stop EC2 instance
        run: |
            export AWS_REGION=ap-south-1
            export AWS_DEFAULT_REGION=ap-south-1
            export AWS_ACCESS_KEY_ID=${{secrets.AWS_ACCESS_KEY_ID }}
            export AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY }}
            aws ec2 start-instances --region ap-south-1 --instance-ids i-06b298be9ed00ddb8
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
